name: flutter_theolive_example
description: Demonstrates how to use the flutter_theolive plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  theolive:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
