name: theolive_platform_interface
description: A common platform interface for the THEOlive Flutter SDK. Used by the platform-specific packages of `theolive`.
version: 1.0.0
homepage: https://theo.live
repository: https://github.com/THEOplayer/theolive-flutter-sdk

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"
  
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^12.0.0
  build_runner: ^2.4.6

topics:
  - theolive
  - low-latency
  - video
