name: theolive_android
description: THEOlive Flutter SDK for Android. Used by `theolive` to support ultra low-latency video playback on Android platforms.
version: 1.0.1
homepage: https://theo.live
repository: https://github.com/THEOplayer/flutter-theolive-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  theolive_platform_interface: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: theolive
    platforms:
      android:
        package: com.theolive.flutter
        pluginClass: FlutterTheolivePlugin
        dartPluginClass: THEOliveAndroid

topics:
  - theolive
  - low-latency
  - video
  