name: theolive_ios
description: THEOlive Flutter SDK for iOS. Used by `theolive` to support ultra low-latency video playback on the iOS platform.
version: 1.0.2
homepage: https://theo.live
repository: https://github.com/THEOplayer/flutter-theolive-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  theolive_platform_interface: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterTheolivePlugin
        dartPluginClass: THEOliveIOS

topics:
  - theolive
  - video
  - low-latency
  